function data = limit_datasites(data,min_num)


load ll.mat;

data.Lock1.WQ_OGM_POC = lowerlakes.Lock1.WQ_OGM_POC;

XX = 309703.3;
YY = 6062973;
data.EPA2014_Coorong_Murray_Mouth = [];

data.EPA2014_Coorong_Murray_Mouth = data.EPA_Monument;

vars = fieldnames(data.EPA2014_Coorong_Murray_Mouth);
for ii = 1:length(vars)
    data.EPA2014_Coorong_Murray_Mouth.(vars{ii}).X =XX;
    data.EPA2014_Coorong_Murray_Mouth.(vars{ii}).Y =YY;
end
    
clear lowerlakes;

sites = fieldnames(data);
for i = 1:length(sites)
    
    vars = fieldnames(data.(sites{i}));
    
    for j = 1:length(vars)
        
        
        if length(data.(sites{i}).(vars{j}).Data) < min_num
            dat.(sites{i}) = rmfield(data.(sites{i}),vars{j});
            disp(['Removing ',vars{j},' from ',sites{i}]);
        end
    end
    
    vars = fieldnames(data.(sites{i}));
    
    if isempty(vars)
        data = rmfield(data,sites{i});
    end
end

% if isfield(data,'VH')
%     data.VH = rmfield(data.VH,'WQ_PHY_GRN');
% end




data.A4261039.SAL.Data(1:length(data.A4261039.SAL.Data),1) = 35;





nsites ={...
    'EPA2014_Coorong_Jockwar_Road',...
'EPA_Jockwar',...
    'A4260902',...
    'Hindmarsh_Island_Boggy_Creek_1',...
    'Hindmarsh_Island_Boggy_Creek_2',...
    'Hindmarsh_Island_Boggy_Creek_3',...
    'Hindmarsh_Island_Boggy_Creek_4',...
    'Hindmarsh_Island_Boggy_Creek_5',...
    'Hindmarsh_Island_Boggy_Creek_6',...
    'Hindmarsh_Island_Boggy_Creek_7',...
    'Hindmarsh_Island_Estick_Creek_2',...
    'Hindmarsh_Island_Estick_Creek_3',...
    'Hindmarsh_Island_Estick_Creek_4',...
    'Hindmarsh_Island_Estick_Creek_5',...
    'Hindmarsh_Island_Hunters_Creek_1',...
    'Hindmarsh_Island_Hunters_Creek_2',...
    'Hindmarsh_Island_Hunters_Creek_3',...
    'Hindmarsh_Island_Hunters_Creek_4',...
    'Hindmarsh_Island_Hunters_Creek_5',...
    'Hindmarsh_Island_Hunters_Creek_6',...
    'Hindmarsh_Island_Mundoo_Channel_1',...
    'Hindmarsh_Island_Mundoo_Channel_2',...
    'Lake_Alexandrina_Boggy_Lake_1',...
    'Lake_Alexandrina_Boggy_Lake_10',...
    'Lake_Alexandrina_Boggy_Lake_11',...
    'Lake_Alexandrina_Boggy_Lake_12',...
    'Lake_Alexandrina_Boggy_Lake_13',...
    'Lake_Alexandrina_Boggy_Lake_14',...
    'Lake_Alexandrina_Boggy_Lake_15',...
    'Lake_Alexandrina_Boggy_Lake_16',...
    'Lake_Alexandrina_Boggy_Lake_17',...
    'Lake_Alexandrina_Boggy_Lake_18',...
    'Lake_Alexandrina_Boggy_Lake_19',...
    'Lake_Alexandrina_Boggy_Lake_2,',...
    'Lake_Alexandrina_Boggy_Lake_20',...
    'Lake_Alexandrina_Boggy_Lake_21',...
    'Lake_Alexandrina_Boggy_Lake_22',...
    'Lake_Alexandrina_Boggy_Lake_23',...
    'Lake_Alexandrina_Boggy_Lake_24',...
    'Lake_Alexandrina_Boggy_Lake_25',...
    'Lake_Alexandrina_Boggy_Lake_26',...
    'Lake_Alexandrina_Boggy_Lake_27',...
    'Lake_Alexandrina_Boggy_Lake_28',...
    'Lake_Alexandrina_Boggy_Lake_29',...
    'Lake_Alexandrina_Boggy_Lake_3,',...
    'Lake_Alexandrina_Boggy_Lake_30',...
    'Lake_Alexandrina_Boggy_Lake_31',...
    'Lake_Alexandrina_Boggy_Lake_32',...
    'Lake_Alexandrina_Boggy_Lake_33',...
    'Lake_Alexandrina_Boggy_Lake_34',...
    'Lake_Alexandrina_Boggy_Lake_35',...
    'Lake_Alexandrina_Boggy_Lake_36',...
    'Lake_Alexandrina_Boggy_Lake_37',...
    'Lake_Alexandrina_Boggy_Lake_38',...
    'Lake_Alexandrina_Boggy_Lake_39',...
    'Lake_Alexandrina_Boggy_Lake_4',...
    'Lake_Alexandrina_Boggy_Lake_40',...
    'Lake_Alexandrina_Boggy_Lake_41',...
    'Lake_Alexandrina_Boggy_Lake_42',...
    'Lake_Alexandrina_Boggy_Lake_43',...
    'Lake_Alexandrina_Boggy_Lake_44',...
    'Lake_Alexandrina_Boggy_Lake_5',...
    'Lake_Alexandrina_Boggy_Lake_6',...
    'Lake_Alexandrina_Boggy_Lake_7',...
    'Lake_Alexandrina_Boggy_Lake_8',...
    'Lake_Alexandrina_Boggy_Lake_9',...
    'VH',...
    'SAW_Blanchetown_Raw',...
    'EPA2014_Lake_Alexandrina_Wellington',...
    'EPA2014_LMRIA_Plume_Toora',...
    'SAW2017_Blanchetown',...
    'EPA2014_Hindmarsh_Island_Hunters_Creek_5',...
    };


for i = 1:length(nsites)
    if isfield(data,nsites{i})
        if isfield(data,nsites{i})==1
        data = rmfield(data,nsites{i});
        end
    end
end


load Pump.mat

sites = fieldnames(pump);
for i = 1:length(sites)
    
    if ~isfield(data,sites{i})
        
        data.(sites{i}) = pump.(sites{i});
    else
        vars = fieldnames(pump.(sites{i}));
        for j = 1:length(vars)
            if ~isfield(data.(sites{i}),vars{j})
                data.(sites{i}).(vars{j}) = pump.(sites{i}).(vars{j});
            else
                data.(sites{i}).(vars{j}).Data = [data.(sites{i}).(vars{j}).Data;pump.(sites{i}).(vars{j}).Data];
                data.(sites{i}).(vars{j}).Date = [data.(sites{i}).(vars{j}).Date;pump.(sites{i}).(vars{j}).Date];
                %                 lowerlakes.(sites{i}).(vars{j}).Depth = [lowerlakes.(sites{i}).(vars{j}).Depth;ll_2015.(sites{i}).(vars{j}).Depth];
            end
        end
    end
end


data = rmfield(data,'Lock1');


% 
% 
% s2017 = {...
%     'SAW2017_Goolwa_US',...
%     'SAW2017_Milang',...
%     'SAW2017_Murray_Bridge_SP',...
%     'SAW2017_Cowirra',...
%     'SAW2017_Mannum',...
%     'SAW2017_Mypolonga',...
%     'SAW2017_Tailem_Bend',...
%     'SAW2017_Swan_Reach_Town',...
%     'SAW2017_Cadell',...
%     'SAW2017_Waikerie_SP',...
%     'SAW2017_Woolpunda_SP',...
%     'SAW2017_Moorook',...
%     'SAW2017_Cobdogla',...
%     'SAW2017_Loxton',...
%     'SAW2017_Berri',...
%     'SAW2017_Renmark_SP',...
%     'SAW2017_DS_lock6_11km',...
%     'SAW2017_Swan_Reach_SP',...
%     'SAW2017_Morgan',...
%     };
% 
% 
% for kk = 1:length(s2017)
%     
%     if isfield(data,regexprep(s2017{kk},'2017',''));
%         old_site = regexprep(s2017{kk},'2017','');
%         new_site = s2017{kk};
%         
%         
%         
%         
%         
%         vars = fieldnames(data.(new_site));
%         
%         for ii = 1:length(vars)
%             if isfield(data.(old_site),vars{ii})
%                 
%                 sss = find(data.(new_site).(vars{ii}).Date >= datenum(2016,07,01));
%                 ttt = find(data.(old_site).(vars{ii}).Date < datenum(2016,07,01));
%                 if ~isempty(sss)
%                     
%                  data.(old_site).(vars{ii}).Date = data.(old_site).(vars{ii}).Date(ttt);   
%                  data.(old_site).(vars{ii}).Data = data.(old_site).(vars{ii}).Data(ttt); 
%                  data.(old_site).(vars{ii}).Depth = [];
%                  
%                 data.(old_site).(vars{ii}).Date = [data.(old_site).(vars{ii}).Date;data.(new_site).(vars{ii}).Date(sss)];
%                 data.(old_site).(vars{ii}).Data = [data.(old_site).(vars{ii}).Data;data.(new_site).(vars{ii}).Data(sss)];
%                 data.(old_site).(vars{ii}).Depth(1:length(data.(old_site).(vars{ii}).Data),1) = 0;
%                 end
%             end
%         end
%         
%         data = rmfield(data,new_site);
%         
%     end
% end


% data.SAW_Swan_Reach_SP = rmfield(data.SAW_Swan_Reach_SP,'WQ_OGM_DOP');
% data.SAW_Swan_Reach_SP = rmfield(data.SAW_Swan_Reach_SP,'WQ_OGM_POP');


end


