clear all; close all;

addpath(genpath('Functions'));

outdir = 'BCs_CEW_barrages_2020/';

if ~exist(outdir,'dir')
    mkdir(outdir);
end

load lowerlakes.mat;


lowerlakes = limit_datasites(lowerlakes,1);

datearray(:,1) = datenum(2012,01,01,00,00,00):1:datenum(2020,07,01,00,00,00);


% headers = {...
%     'FLOW',...
%     'SAL',...
%     'TEMP',...
%     'TRACE_1',...
%     'WQ_TRC_SS1',...
% 'WQ_TRC_RET',...
% 'WQ_OXY_OXY',...
% 'WQ_CAR_DIC',...
% 'WQ_CAR_PH',...
% 'WQ_CAR_CH4',...
% 'WQ_SIL_RSI',...
% 'WQ_NIT_AMM',...
% 'WQ_NIT_NIT',...
% 'WQ_NIT_N2O',...
% 'WQ_PHS_FRP',...
% 'WQ_PHS_FRP_ADS',...
% 'WQ_OGM_DOC',...
% 'WQ_OGM_POC',...
% 'WQ_OGM_DON',...
% 'WQ_OGM_PON',...
% 'WQ_OGM_DOP',...
% 'WQ_OGM_POP',...
% 'WQ_PHY_GRN',...
% 'WQ_ZOO_GRAZER',...
% 'WQ_GEO_PE',...
% 'WQ_GEO_UBALCHG',...
% 'WQ_LND_TRACER',...
% 'WQ_SBG_TRACER',...
% 'WQ_SBG_DOM_LEACHATE',...
%     };

headers = {...
    'FLOW',...
    'SAL',...
    'TEMP',...
    'TRACE_1',...
    'WQ_TRC_AGE',...
    'WQ_NCS_SS1',...
'WQ_OXY_OXY',...
'WQ_SIL_RSI',...
'WQ_NIT_AMM',...
'WQ_NIT_NIT',...
'WQ_PHS_FRP',...
'WQ_PHS_FRP_ADS',...
'WQ_OGM_DOC',...
'WQ_OGM_POC',...
'WQ_OGM_DON',...
'WQ_OGM_PON',...
'WQ_OGM_DOP',...
'WQ_OGM_POP',...
'WQ_PHY_GRN',...
    };

% filename = [outdir,'Chowilla_Lock6.csv'];
% subdir = [outdir,'Chowilla_Lock6/'];
% 
% X = 489466.7;
% Y = 6238325.5;
% 
% create_tfv_inflow_file(lowerlakes,headers,datearray,filename,X,Y,subdir,'Chowilla_Lock6');
% 
% 
% 
% 
% %
% 
% filename = [outdir,'Chowilla_Lock5.csv'];
% subdir = [outdir,'Chowilla_Lock5/'];
% 
% X = 478506.1;
% Y = 6216905.4;
% 
% create_tfv_inflow_file(lowerlakes,headers,datearray,filename,X,Y,subdir,'Chowilla_Lock5');
% 
% 
% %headers{1} = 'H';
% filename = [outdir,'Chowilla_Chowilla_Creek.csv'];
% subdir = [outdir,'Chowilla_Chowilla_Creek/'];
% 
% X = 487239;
% Y = 6239358;
% 
% create_tfv_inflow_file(lowerlakes,headers,datearray,filename,X,Y,subdir,'Chowilla_Chowilla_Creek');
% 
% headers{1} = 'H';
%  filename = [outdir,'Chowilla_Lock5_H.csv'];
% subdir = [outdir,'Chowilla_Lock5_H/'];
% 
% X = 478506.1;
% Y = 6216905.4;
% 
% create_tfv_inflow_file(lowerlakes,headers,datearray,filename,X,Y,subdir,'Chowilla_Lock5');


% % 
% % % 
% % % % ____________________________________________________

outfile = {'Tauwitchere_v3';'Ewe_v3';'Boundary_v3';'Mundoo_v3';'Goolwa_v3';};
	
	pnt(1,1) = 319928.0;
	pnt(1,2) = 6060308.0;
	
	pnt(2,1) = 316253.0;
	pnt(2,2) = 6062708.0;
	
	
	pnt(3,1) = 314279.0;
	pnt(3,2) = 6063808.0;
	
	pnt(4,1) = 310144.0;
	pnt(4,2) = 6063808.0;
	
	pnt(5,1) = 300360.0;
	pnt(5,2) = 6066992.0;

for ii=1:length(outfile)    
    
    filename = [outdir,outfile{ii},'.csv'];
    subdir = [outdir,outfile{ii},'/'];

X = pnt(ii,1);
Y = pnt(ii,2);

create_tfv_inflow_file(lowerlakes,headers,datearray,filename,X,Y,subdir,outfile{ii});
end


create_html_for_directory(outdir);
